version: '3'
services:
  nginx:
    build: ./nginx/.
    ports:
      - 8000:80
    volumes:
      - ./app:/var/www/html
    depends_on:
      - app
      - db

  app:
    build: ./php/.
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    build: ./mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: 'common'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql/mysql_volume:/var/lib/mysql
